@echo off
color 81
goto main

:main
title optimizer
cls
echo ==============================================================
echo 1.RAM
echo 2.GPU
echo 3.CPU
echo 4.MTU
echo 5.delete temporary files
echo 6.help
echo 7.exit
echo ==============================================================
set /p var=Select an option:
if %var%==1 goto RAM
if %var%==2 goto GPU
if %var%==3 goto CPU
if %var%==4 goto MTU
if %var%==5 goto deltemp
if %var%==6 goto help
if %var%==7 exit

:GPU
setx GPU_FORCE_64BIT_PTR 0
::you can set this option to 1 for mining,sharing resources or servers::
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
goto main
pause>nul

:CPU
setx CPU_FORCE_64BIT_PTR 0
::you can set this option to 1 for mining,sharing resources or servers::
setx CPU_MAX_HEAP_SIZE 100
setx CPU_USE_SYNC_OBJECTS 1
setx CPU_MAX_ALLOC_PERCENT 100
setx CPU_SINGLE_ALLOC_PERCENT 100
goto main
pause>nul

:RAM
set /p in=How much GB of RAM do you have?
set /a out=!in!*1000/2
bcdedit /set increaseuserva %out%
pause
fsutil behavior set memoryusage 2
goto main_restart
pause>nul

:deltemp
del %temp%
goto main
pause>nul

:MTU
cls
echo ======================================================
echo 1.Wi-fi
echo 2.Ethernet
echo 3.local network
echo 4.go back
echo ======================================================
set /p cn= Select an option:
if %cn%==1 goto wifi
if %cn%==2 goto ethernet
if %cn%==3 goto ln
if %cn%==4 goto main

:wifi
echo you can check this executing in cmd: netsh interface ipv4 show interfaces
set /p mtu= whats your MTU?
netsh int ipv4 set subinterface "Wi-Fi" mtu = %mtu% store = persistent
goto main
pause>nul

:ethernet
echo you can check this executing in cmd:netsh interface ipv4 show interfaces
set /p mtu= whats your MTU?
netsh int ipv4 set subinterface "Ethernet" mtu = %mtu% store = persistent
goto main
pause>nul

:ln
echo you can check this executing in cmd:netsh interface ipv4 show interfaces
set /p mtu= whats your MTU?
netsh int ipv4 set subinterface "Local Network" mtu = %mtu% store = persistent
goto main
pause>nul

:help
cls
echo ============================================
echo 1.RAM
echo 2.GPU
echo 3.CPU
echo 4.MTU
echo 5.delete temporary files
echo 6.go back
echo ============================================
set /p help= Select an option:
if %help%==1 goto help_RAM
if %help%==2 goto help_GPU
if %help%==3 goto help_CPU
if %help%==4 goto help_MTU
if %help%==5 goto help_temp
if %help%==6 goto main

:help_RAM
cls
echo All instructions executed by the CPU(Central Processing Unit),program data and another parts of the pc are echo loaded into RAM(Random Access Memory).
pause>nul
goto help

:help_GPU
cls
echo The GPU(Graphical Processing Unit) helps renders all the things on screen and is dedicated to
echo graphics processing and floating comma operations.
pause>nul
goto help

:help_CPU
cls
echo The CPU(Central Processing Unit) is used to interpret the instructions of the programs.
pause>nul
goto help

:help_MTU
cls
echo MTU(Maximum Transmission Unit) defines how much a packet of bytes can send by the internet connection
pause>nul
goto help

:help_temp
cls
echo a temporary file is a file that is generated by a program so that if you lose any data
echo you can use the program normally
pause>nul
goto help

:main_restart
cls
title restart to save changes
echo ==========
echo 1.restart
echo 2.go back
echo ==========
set /p restart= Select an option:
if %restart%==1 goto restart
if %restart%==2 goto main
:restart
shutdown -r -t 1
exit
